### ISSUE TITLE
Unable to initialize Vlocode on vscode

### ISSUE THREAD

**Issue by ShreyasD** [Codeneos/vlocode#397] opened 2023-03-08 16:45 UTC
Getting the following error when trying to initialize Vlocode plugin in vscode. 

**Vscode Info**
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

**Comment by a470836-abloomfield** [comment] 2023-03-09 18:22
did you look at issue #395 ?

**Comment by Codeneos** [comment] 2023-03-10 10:55
@ShreyasD as suggested by @a470836-abloomfield I will need some extra details to understand the root cause. You can get more details and a stacktrace from the developer logs from vscode which can be enabled through the `Help > Toggle Developer Console` item.

**Comment by Codeneos** [comment] 2023-04-24 15:34
Closing this issue 0.19.x branch will hopefully have fixed this issue

**Closed by Codeneos** 2023-04-24 15:34 UTC
