### ISSUE TITLE
 Extension curlybracket.vlocode has provided an invalid tree item - error is caused by 'Document Template' datapack

### ISSUE THREAD

**Issue by strzelaczinho** [Codeneos/vlocode#389] opened 2022-10-17 14:29 UTC
Hey i am facing an issue while trying to retrieve 'Document Template' vlocity DataPack from environment. Error is showing up only on 'Document Templates' . For example retrieving DataRaptors works fine. It seems there is some badly written object name on that retrieval.  Can you tell what can cause the problem ? I can only see the error when i click refresh button - there are no logs and no other information is available.
![image](https://user-images.githubusercontent.com/33316344/196203373-5dbba394-f9f2-45e6-b7c6-597d4ae3a312.png)

**Comment by strzelaczinho** [comment] 2022-10-17 17:58
It is happening on latest version of the extenstion as well as the oldest ones.
![image](https://user-images.githubusercontent.com/33316344/196249083-916ba80d-2097-453f-ad43-d3831acab4e7.png)

**Comment by strzelaczinho** [comment] 2022-10-17 18:55
![save2](https://user-images.githubusercontent.com/33316344/196259390-745ba0ce-2bf1-4d9e-b652-5257ece2e942.gif)

**Comment by Codeneos** [comment] 2022-10-17 22:23
Thanka for reporting. Not sure what is causing this as it seems to be working fine on the previous version of vscode.

You can enable debug logging from vlocode settings, it will print some additionaldebug info into the logs. Additional logging from vscode itself is availble through help > enable developers tools. 

If you are on the latest version of vscode could you try to downgrade vscode to 1.71?

**Comment by strzelaczinho** [comment] 2022-10-19 13:18
I will try to downgrade VScode somewhere around the weekend . Right now i am just pasting dev console logs.
![save3](https://user-images.githubusercontent.com/33316344/196701978-c5fbf3fc-6672-4756-9bc0-1ce9050de61e.gif)

**Comment by Codeneos** [comment] 2022-10-19 16:28
@strzelaczinho thanks for the recording, it was very helpful.

I have pinpointed the root cause and will release a fix in the upcoming release **0.17.12** which should be out in a couple of hours.

**Comment by Codeneos** [comment] 2022-10-19 16:31
Release is available on github [here](https://github.com/Codeneos/vlocode/releases/tag/v0.17.12) should be available on the vscode marketplace in a few minutes as well.

let me know if the new release fixes the issue

**Comment by Codeneos** [comment] 2022-10-23 10:35
Closing this aa fixed.

**Closed by Codeneos** 2022-10-23 10:35 UTC
Labels: bug

**Comment by strzelaczinho** [comment] 2022-10-29 11:39
Yes it seems the newest version made it. I totally forgot about reporting back to you with the Visual Code version thing ( i did not downgrade at all , sorry for that ) on the working solution but that bug you have lately fixed could have been overidden by exporting all the Teampltes from Document Template folder. Thanks for the help . Have a good day : )

**Comment by Codeneos** [comment] 2022-10-31 13:17
I hope the latest version of Vlocode fixed the issues with the DocumentTemplate export 👍
