### ISSUE TITLE
[error] Command error: Found non-callable @@iterator

### ISSUE THREAD

**Issue by SebTub** [Codeneos/vlocode#384] opened 2022-08-18 07:57 UTC
Hey Team,
The Salesforce Vlocity Integration add-on was working like a charm. I was able to download the Vlocity components and today I have got an error message :"[error] Command error: Found non-callable @@iterator"
Could you help please?

Here's the log:
[19:39:56.59] [CommandRouter] [info] Registered 32 vscode commands
[19:39:56.59] [vlocode] [info] Vlocode version 0.17.4 started
[19:39:56.59] [vlocode] [info] Using built tools version 1.14.18
[19:39:56.59] [VlocodeService] [info] Salesforce support enabled
[19:39:56.59] [MetadataRegistry] [warn] XML Name already in-use: oauthcustomscope
[19:39:56.60] [WorkspaceContextDetector] [info] Probing workspace a..... (/c:/Users/...) for datapacks...
[19:39:56.60] [WorkspaceContextDetector] [info] Probing workspace a... (/c:/Users/...) for metadata...
[19:39:56.60] [vlocode] [info] Vlocode activated in 780ms
[19:39:56.60] [VlocodeService] [info] Salesforce developer logs view enabled
[19:39:59.59] [WorkspaceContextDetector] [info] Detected 558 applicable files for context [datapacks] in workspace a... [2992ms]
[19:39:59.59] [WorkspaceContextDetector] [info] Detected 1159 applicable files for context [metadata] in workspace a... [2994ms]
[19:40:00.22] [JobDataProvider] [info] Found 0 YAML files in workspace folders
[19:40:00.22] [JobDataProvider] [info] Displaying 0 valid Job files in Job explorer
[19:40:01.16] [VlocityNamespaceService] [info] Initialized Vlocity namespace to vlocity_cmt [621ms]
[19:40:01.17] [vlocity] [info] Org username@blurb.com
[19:40:10.35] [SchemaAccess] [info] Described 1 objects and field metadata in 1541ms
[19:40:12.99] [Connection] [error] Error: NOT_FOUND The requested resource does not exist - vlocity_cmt__QueryBuilder__c
[19:40:13.24] [Connection] [error] Error: NOT_FOUND The requested resource does not exist - vlocity_cmt__VlocityDataStore__c
[19:40:14.07] [Connection] [error] Error: NOT_FOUND The requested resource does not exist - vlocity_cmt__ObjectContextRule__c
[19:40:14.90] [Connection] [error] Error: NOT_FOUND The requested resource does not exist - vlocity_cmt__PublicProgram__c
[19:40:17.70] [SchemaAccess] [info] Described 100 objects and field metadata in 6532ms
[19:40:17.70] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__ObjectContextRule__c: matching key field '%vlocity_namespace%__GlobalKey__c' is invalid or not accessible
[19:40:17.70] [VlocityMatchingKeyService] [warn] PricebookEntry: matching key field 'CurrencyIsoCode' is invalid or not accessible
[19:40:17.70] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__PublicProgram__c: matching key field 'Name' is invalid or not accessible
[19:40:17.70] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__QueryBuilder__c: matching key field 'Name' is invalid or not accessible
[19:40:17.70] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__VlocityDataStore__c: matching key field 'Name' is invalid or not accessible
[19:40:19.40] [SchemaAccess] [info] Described 1 objects and field metadata in 1644ms
[19:40:20.39] [VlocityMatchingKeyService] [info] Loaded 101 matching keys definitions from Salesforce
[19:40:31.89] [SelectOrgCommand] [info] Set username@blurb.com as target org for Vlocity deploy/refresh operations
[19:40:34.92] [VlocityNamespaceService] [info] Initialized Vlocity namespace to vlocity_cmt [668ms]
[19:40:34.92] [vlocity] [info] Org username@blurb.com
[19:40:43.22] [DatapackDataProvider] [info] Found 1 exportable datapacks form type ContextScope
[19:40:43.53] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__ObjectContextRule__c: matching key field '%vlocity_namespace%__GlobalKey__c' is invalid or not accessible
[19:40:43.53] [VlocityMatchingKeyService] [warn] PricebookEntry: matching key field 'CurrencyIsoCode' is invalid or not accessible
[19:40:43.53] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__PublicProgram__c: matching key field 'Name' is invalid or not accessible
[19:40:43.53] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__QueryBuilder__c: matching key field 'Name' is invalid or not accessible
[19:40:43.53] [VlocityMatchingKeyService] [warn] %vlocity_namespace%__VlocityDataStore__c: matching key field 'Name' is invalid or not accessible
[19:40:43.54] [VlocityMatchingKeyService] [info] Loaded 101 matching keys definitions from Salesforce
[19:40:49.02] [CommandExecutor] [error] Command error: Found non-callable @@iterator
[19:41:18.58] [SchemaAccess] [info] Described 1 objects and field metadata in 9733ms
[19:41:22.55] [CommandExecutor] [error] Command error: Found non-callable @@iterator

**Comment by Codeneos** [comment] 2022-08-19 07:17
Thanks for the report! Were you trying to run a specific command (if so which command) or did you just get this error when the extension started?

**Comment by Codeneos** [comment] 2022-08-19 07:50
Root cause found, this issue will be fixed in v0.17.5

**Comment by SebTub** [comment] 2022-08-21 22:24
Sorry Codenos,
I forgot to mention how to reproduce the issue.
That happens when we want to export some Vlocity Components through the Add-on.
Do you know when the fix will be released?

Thanks a lot again, it's a very great app!

**Comment by Codeneos** [comment] 2022-08-22 11:01
Update should be available; if you don't get the update offered you can always manually download from the [github releases section](https://github.com/Codeneos/vlocode/releases/tag/v0.17.5)

**Comment by omgitscurii** [comment] 2022-09-14 08:27
Hi, sorry to comment on a closed issue but this still happens to me, even in v0.17.6.

Whenever I export a Product2 object, I don't get the related PriceListEntries.json. This is observed after the upgrade to CMT 238, where these new fields were introduced (the ones mentioned in this issue log): vlocity_cmt__QueryBuilder__c, vlocity_cmt__VlocityDataStore__c, vlocity_cmt__ObjectContextRule__c, vlocity_cmt__PublicProgram__c

**Comment by Codeneos** [comment] 2022-09-14 21:45
No problem. The not found errors are ok, or atleast they are harmless. This happens due to the Vlocity CMT package containing configuration in the datapack mdt table for datapacks for which the sobjects don't t exist or are not accessible outside of the managed package code.

Try to create an empty `.vlocode` file with just `{} ` which could help by starting the extension earlier.

I won't be able to look at the issue this week due to holidays, but start of next week I will have a look. I might ask you for ome extra debug logs to pin point the issue.

**Comment by omgitscurii** [comment] 2022-09-15 09:19
[log_debugLevel.txt](https://github.com/Codeneos/vlocode/files/9573811/log_debugLevel.txt)

Here's the log (Log level: debug) from the moment I open VSCode.

**Comment by Codeneos** [comment] 2022-09-29 14:01
@omgitscurii I did a few checks and the error is harmless, I did change error to a warning.

Let me know if you encounter any export issues still

**Comment by omgitscurii** [comment] 2022-09-29 18:36
@Codeneos, thanks for checking this up!
Sorry but the export problem was unrelated to this issue, I didn't debug it properly.
All good!

**Comment by Codeneos** [comment] 2022-10-07 07:06
No problem! Closing the bug :)

**Closed by Codeneos** 2022-10-07 07:06 UTC
Labels: bug
