### ISSUE TITLE
Command error: Vlocode is not initialized; VlocityDatapackService is null

### ISSUE THREAD

**Issue by shishirbansal** [Codeneos/vlocode#395] opened 2022-12-15 03:17 UTC
### Discussed in https://github.com/Codeneos/vlocode/discussions/394

<div type='discussions-op-text'>

<sup>Originally posted by **shishirbansal** December 15, 2022</sup>
Hi,

OS : MAC (12.6.1) Monterey
SF cli : sfdx-cli/7.180.0 darwin-x64 node-v18.12.1
Vs Code Version : 1.74.0 (Universal)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0

Recently i am not able to use the Vlocity VScode extension. I tried to uninstall the extension and salesforce one and then VS code also. Reinstalled everything from scratch and able to work with Salesforce extension but not able to connect the org for vlocity. Even cleaned the alias and logged out from all the orgs in terminal and started with just one org but no luck. I am attaching the screenshot. Please let me know if there is something that is missing from my end or if this is a known issue.

<img width="1300" alt="VsCode" src="https://user-images.githubusercontent.com/23053736/207762831-494df402-5b82-42c9-b513-78426c819dd7.png">
</div>

**Comment by shishirbansal** [comment] 2022-12-28 07:12
Hi @Codeneos , 

Can you help me out on this or guide

**Comment by Codeneos** [comment] 2023-01-19 09:27
@shishirbansal thanks for reporting the issue! Can you provide some additional debug logs from the vscode developer console to help pinpoint the root cause?

You can access view the developer console messages from `Help > Toggle Developer Console` in vscode
![image](https://user-images.githubusercontent.com/787686/213405071-8c31abe9-4f02-47d5-ab4a-9eedcd5e5555.png)

**Comment by Codeneos** [comment] 2023-04-24 15:35
Closing this issue 0.19.x branch will hopefully have fixed this issue

**Closed by Codeneos** 2023-04-24 15:35 UTC

**Comment by shishirbansal** [comment] 2023-05-04 05:26
Hello @Codeneos , 

My apologise for the reply i am here . When i try to click on Help > Toggle Developer Console. It is opening Chrome developer tools. 
![Uploading Screenshot 2023-05-04 at 10.54.54 AM.png…]()

**Comment by shishirbansal** [comment] 2023-05-04 05:43
I am getting this error when i reinstalled it
![Screenshot 2023-05-04 at 11 13 00 AM](https://user-images.githubusercontent.com/23053736/236120879-64fbf826-399a-436a-bf19-551765dfd928.png)
